version: '3.8'
services:
  mongoDp:
    image: mongo:latest
    container_name: mongoDp
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: article-server
    depends_on:
      - mongoDp
    environment:
      - MONGODB_URI=mongodb://mongoDp:27017
    ports:
      - "50051:50051"
    restart: unless-stopped
    # Wait for MongoDB to be ready before starting
    entrypoint: ["/bin/sh", "-c", "until nc -z mongoDp 27017; do sleep 1; done; ./article-server"]

volumes:
  mongo_data: 