// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: article.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ArticleService_ProcessArticles_FullMethodName      = "/article.ArticleService/ProcessArticles"
	ArticleService_ProcessSingleArticle_FullMethodName = "/article.ArticleService/ProcessSingleArticle"
	ArticleService_GetTopTags_FullMethodName           = "/article.ArticleService/GetTopTags"
)

// ArticleServiceClient is the client API for ArticleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArticleServiceClient interface {
	// Bidirectional streaming: client sends a stream of requests, server returns a stream of responses
	ProcessArticles(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProcessArticleRequest, ProcessArticleResponse], error)
	// Unary RPC: process a single article and return its tags
	ProcessSingleArticle(ctx context.Context, in *ProcessArticleRequest, opts ...grpc.CallOption) (*ProcessArticleResponse, error)
	// Unary RPC: get the top N most frequent tags across all articles
	GetTopTags(ctx context.Context, in *GetTopTagsRequest, opts ...grpc.CallOption) (*GetTopTagsResponse, error)
}

type articleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArticleServiceClient(cc grpc.ClientConnInterface) ArticleServiceClient {
	return &articleServiceClient{cc}
}

func (c *articleServiceClient) ProcessArticles(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ProcessArticleRequest, ProcessArticleResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ArticleService_ServiceDesc.Streams[0], ArticleService_ProcessArticles_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProcessArticleRequest, ProcessArticleResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ArticleService_ProcessArticlesClient = grpc.BidiStreamingClient[ProcessArticleRequest, ProcessArticleResponse]

func (c *articleServiceClient) ProcessSingleArticle(ctx context.Context, in *ProcessArticleRequest, opts ...grpc.CallOption) (*ProcessArticleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessArticleResponse)
	err := c.cc.Invoke(ctx, ArticleService_ProcessSingleArticle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleServiceClient) GetTopTags(ctx context.Context, in *GetTopTagsRequest, opts ...grpc.CallOption) (*GetTopTagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTopTagsResponse)
	err := c.cc.Invoke(ctx, ArticleService_GetTopTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArticleServiceServer is the server API for ArticleService service.
// All implementations must embed UnimplementedArticleServiceServer
// for forward compatibility.
type ArticleServiceServer interface {
	// Bidirectional streaming: client sends a stream of requests, server returns a stream of responses
	ProcessArticles(grpc.BidiStreamingServer[ProcessArticleRequest, ProcessArticleResponse]) error
	// Unary RPC: process a single article and return its tags
	ProcessSingleArticle(context.Context, *ProcessArticleRequest) (*ProcessArticleResponse, error)
	// Unary RPC: get the top N most frequent tags across all articles
	GetTopTags(context.Context, *GetTopTagsRequest) (*GetTopTagsResponse, error)
	mustEmbedUnimplementedArticleServiceServer()
}

// UnimplementedArticleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArticleServiceServer struct{}

func (UnimplementedArticleServiceServer) ProcessArticles(grpc.BidiStreamingServer[ProcessArticleRequest, ProcessArticleResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ProcessArticles not implemented")
}
func (UnimplementedArticleServiceServer) ProcessSingleArticle(context.Context, *ProcessArticleRequest) (*ProcessArticleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessSingleArticle not implemented")
}
func (UnimplementedArticleServiceServer) GetTopTags(context.Context, *GetTopTagsRequest) (*GetTopTagsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopTags not implemented")
}
func (UnimplementedArticleServiceServer) mustEmbedUnimplementedArticleServiceServer() {}
func (UnimplementedArticleServiceServer) testEmbeddedByValue()                        {}

// UnsafeArticleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArticleServiceServer will
// result in compilation errors.
type UnsafeArticleServiceServer interface {
	mustEmbedUnimplementedArticleServiceServer()
}

func RegisterArticleServiceServer(s grpc.ServiceRegistrar, srv ArticleServiceServer) {
	// If the following call pancis, it indicates UnimplementedArticleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArticleService_ServiceDesc, srv)
}

func _ArticleService_ProcessArticles_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ArticleServiceServer).ProcessArticles(&grpc.GenericServerStream[ProcessArticleRequest, ProcessArticleResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ArticleService_ProcessArticlesServer = grpc.BidiStreamingServer[ProcessArticleRequest, ProcessArticleResponse]

func _ArticleService_ProcessSingleArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessArticleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).ProcessSingleArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleService_ProcessSingleArticle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).ProcessSingleArticle(ctx, req.(*ProcessArticleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleService_GetTopTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).GetTopTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleService_GetTopTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).GetTopTags(ctx, req.(*GetTopTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ArticleService_ServiceDesc is the grpc.ServiceDesc for ArticleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArticleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "article.ArticleService",
	HandlerType: (*ArticleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessSingleArticle",
			Handler:    _ArticleService_ProcessSingleArticle_Handler,
		},
		{
			MethodName: "GetTopTags",
			Handler:    _ArticleService_GetTopTags_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ProcessArticles",
			Handler:       _ArticleService_ProcessArticles_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "article.proto",
}
