// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: article.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Article struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Article) Reset() {
	*x = Article{}
	mi := &file_article_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Article) ProtoMessage() {}

func (x *Article) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Article.ProtoReflect.Descriptor instead.
func (*Article) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{0}
}

func (x *Article) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Article) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type ProcessArticleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Article       *Article               `protobuf:"bytes,1,opt,name=article,proto3" json:"article,omitempty"`
	N             int32                  `protobuf:"varint,2,opt,name=n,proto3" json:"n,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessArticleRequest) Reset() {
	*x = ProcessArticleRequest{}
	mi := &file_article_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessArticleRequest) ProtoMessage() {}

func (x *ProcessArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessArticleRequest.ProtoReflect.Descriptor instead.
func (*ProcessArticleRequest) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessArticleRequest) GetArticle() *Article {
	if x != nil {
		return x.Article
	}
	return nil
}

func (x *ProcessArticleRequest) GetN() int32 {
	if x != nil {
		return x.N
	}
	return 0
}

type ProcessArticleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []string               `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessArticleResponse) Reset() {
	*x = ProcessArticleResponse{}
	mi := &file_article_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessArticleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessArticleResponse) ProtoMessage() {}

func (x *ProcessArticleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessArticleResponse.ProtoReflect.Descriptor instead.
func (*ProcessArticleResponse) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessArticleResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type GetTopTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	N             int32                  `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopTagsRequest) Reset() {
	*x = GetTopTagsRequest{}
	mi := &file_article_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopTagsRequest) ProtoMessage() {}

func (x *GetTopTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopTagsRequest.ProtoReflect.Descriptor instead.
func (*GetTopTagsRequest) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{3}
}

func (x *GetTopTagsRequest) GetN() int32 {
	if x != nil {
		return x.N
	}
	return 0
}

type GetTopTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []string               `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopTagsResponse) Reset() {
	*x = GetTopTagsResponse{}
	mi := &file_article_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopTagsResponse) ProtoMessage() {}

func (x *GetTopTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_article_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopTagsResponse.ProtoReflect.Descriptor instead.
func (*GetTopTagsResponse) Descriptor() ([]byte, []int) {
	return file_article_proto_rawDescGZIP(), []int{4}
}

func (x *GetTopTagsResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_article_proto protoreflect.FileDescriptor

const file_article_proto_rawDesc = "" +
	"\n" +
	"\rarticle.proto\x12\aarticle\"3\n" +
	"\aArticle\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\"Q\n" +
	"\x15ProcessArticleRequest\x12*\n" +
	"\aarticle\x18\x01 \x01(\v2\x10.article.ArticleR\aarticle\x12\f\n" +
	"\x01n\x18\x02 \x01(\x05R\x01n\",\n" +
	"\x16ProcessArticleResponse\x12\x12\n" +
	"\x04tags\x18\x01 \x03(\tR\x04tags\"!\n" +
	"\x11GetTopTagsRequest\x12\f\n" +
	"\x01n\x18\x01 \x01(\x05R\x01n\"(\n" +
	"\x12GetTopTagsResponse\x12\x12\n" +
	"\x04tags\x18\x01 \x03(\tR\x04tags2\x88\x02\n" +
	"\x0eArticleService\x12V\n" +
	"\x0fProcessArticles\x12\x1e.article.ProcessArticleRequest\x1a\x1f.article.ProcessArticleResponse(\x010\x01\x12W\n" +
	"\x14ProcessSingleArticle\x12\x1e.article.ProcessArticleRequest\x1a\x1f.article.ProcessArticleResponse\x12E\n" +
	"\n" +
	"GetTopTags\x12\x1a.article.GetTopTagsRequest\x1a\x1b.article.GetTopTagsResponseB\tZ\a./protob\x06proto3"

var (
	file_article_proto_rawDescOnce sync.Once
	file_article_proto_rawDescData []byte
)

func file_article_proto_rawDescGZIP() []byte {
	file_article_proto_rawDescOnce.Do(func() {
		file_article_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_article_proto_rawDesc), len(file_article_proto_rawDesc)))
	})
	return file_article_proto_rawDescData
}

var file_article_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_article_proto_goTypes = []any{
	(*Article)(nil),                // 0: article.Article
	(*ProcessArticleRequest)(nil),  // 1: article.ProcessArticleRequest
	(*ProcessArticleResponse)(nil), // 2: article.ProcessArticleResponse
	(*GetTopTagsRequest)(nil),      // 3: article.GetTopTagsRequest
	(*GetTopTagsResponse)(nil),     // 4: article.GetTopTagsResponse
}
var file_article_proto_depIdxs = []int32{
	0, // 0: article.ProcessArticleRequest.article:type_name -> article.Article
	1, // 1: article.ArticleService.ProcessArticles:input_type -> article.ProcessArticleRequest
	1, // 2: article.ArticleService.ProcessSingleArticle:input_type -> article.ProcessArticleRequest
	3, // 3: article.ArticleService.GetTopTags:input_type -> article.GetTopTagsRequest
	2, // 4: article.ArticleService.ProcessArticles:output_type -> article.ProcessArticleResponse
	2, // 5: article.ArticleService.ProcessSingleArticle:output_type -> article.ProcessArticleResponse
	4, // 6: article.ArticleService.GetTopTags:output_type -> article.GetTopTagsResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_article_proto_init() }
func file_article_proto_init() {
	if File_article_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_article_proto_rawDesc), len(file_article_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_article_proto_goTypes,
		DependencyIndexes: file_article_proto_depIdxs,
		MessageInfos:      file_article_proto_msgTypes,
	}.Build()
	File_article_proto = out.File
	file_article_proto_goTypes = nil
	file_article_proto_depIdxs = nil
}
