// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: proto/article.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ArticleService_ExtractTags_FullMethodName      = "/article.ArticleService/ExtractTags"
	ArticleService_BatchExtractTags_FullMethodName = "/article.ArticleService/BatchExtractTags"
	ArticleService_GetTopTags_FullMethodName       = "/article.ArticleService/GetTopTags"
)

// ArticleServiceClient is the client API for ArticleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArticleServiceClient interface {
	// Unary RPC: Process one article and extract N tags
	ExtractTags(ctx context.Context, in *Article, opts ...grpc.CallOption) (*TagsResponse, error)
	// Server streaming RPC: Batch process articles concurrently
	BatchExtractTags(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Article, TagsResponse], error)
	// Get top N frequent tags across all articles
	GetTopTags(ctx context.Context, in *TopTagsRequest, opts ...grpc.CallOption) (*TagsResponse, error)
}

type articleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArticleServiceClient(cc grpc.ClientConnInterface) ArticleServiceClient {
	return &articleServiceClient{cc}
}

func (c *articleServiceClient) ExtractTags(ctx context.Context, in *Article, opts ...grpc.CallOption) (*TagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TagsResponse)
	err := c.cc.Invoke(ctx, ArticleService_ExtractTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *articleServiceClient) BatchExtractTags(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Article, TagsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ArticleService_ServiceDesc.Streams[0], ArticleService_BatchExtractTags_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Article, TagsResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ArticleService_BatchExtractTagsClient = grpc.BidiStreamingClient[Article, TagsResponse]

func (c *articleServiceClient) GetTopTags(ctx context.Context, in *TopTagsRequest, opts ...grpc.CallOption) (*TagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TagsResponse)
	err := c.cc.Invoke(ctx, ArticleService_GetTopTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArticleServiceServer is the server API for ArticleService service.
// All implementations must embed UnimplementedArticleServiceServer
// for forward compatibility.
type ArticleServiceServer interface {
	// Unary RPC: Process one article and extract N tags
	ExtractTags(context.Context, *Article) (*TagsResponse, error)
	// Server streaming RPC: Batch process articles concurrently
	BatchExtractTags(grpc.BidiStreamingServer[Article, TagsResponse]) error
	// Get top N frequent tags across all articles
	GetTopTags(context.Context, *TopTagsRequest) (*TagsResponse, error)
	mustEmbedUnimplementedArticleServiceServer()
}

// UnimplementedArticleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArticleServiceServer struct{}

func (UnimplementedArticleServiceServer) ExtractTags(context.Context, *Article) (*TagsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExtractTags not implemented")
}
func (UnimplementedArticleServiceServer) BatchExtractTags(grpc.BidiStreamingServer[Article, TagsResponse]) error {
	return status.Errorf(codes.Unimplemented, "method BatchExtractTags not implemented")
}
func (UnimplementedArticleServiceServer) GetTopTags(context.Context, *TopTagsRequest) (*TagsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopTags not implemented")
}
func (UnimplementedArticleServiceServer) mustEmbedUnimplementedArticleServiceServer() {}
func (UnimplementedArticleServiceServer) testEmbeddedByValue()                        {}

// UnsafeArticleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArticleServiceServer will
// result in compilation errors.
type UnsafeArticleServiceServer interface {
	mustEmbedUnimplementedArticleServiceServer()
}

func RegisterArticleServiceServer(s grpc.ServiceRegistrar, srv ArticleServiceServer) {
	// If the following call pancis, it indicates UnimplementedArticleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArticleService_ServiceDesc, srv)
}

func _ArticleService_ExtractTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Article)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).ExtractTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleService_ExtractTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).ExtractTags(ctx, req.(*Article))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArticleService_BatchExtractTags_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ArticleServiceServer).BatchExtractTags(&grpc.GenericServerStream[Article, TagsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ArticleService_BatchExtractTagsServer = grpc.BidiStreamingServer[Article, TagsResponse]

func _ArticleService_GetTopTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TopTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArticleServiceServer).GetTopTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArticleService_GetTopTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArticleServiceServer).GetTopTags(ctx, req.(*TopTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ArticleService_ServiceDesc is the grpc.ServiceDesc for ArticleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArticleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "article.ArticleService",
	HandlerType: (*ArticleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExtractTags",
			Handler:    _ArticleService_ExtractTags_Handler,
		},
		{
			MethodName: "GetTopTags",
			Handler:    _ArticleService_GetTopTags_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BatchExtractTags",
			Handler:       _ArticleService_BatchExtractTags_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/article.proto",
}
