// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/article.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Article struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Article) Reset() {
	*x = Article{}
	mi := &file_proto_article_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Article) ProtoMessage() {}

func (x *Article) ProtoReflect() protoreflect.Message {
	mi := &file_proto_article_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Article.ProtoReflect.Descriptor instead.
func (*Article) Descriptor() ([]byte, []int) {
	return file_proto_article_proto_rawDescGZIP(), []int{0}
}

func (x *Article) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Article) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type TagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []string               `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagsResponse) Reset() {
	*x = TagsResponse{}
	mi := &file_proto_article_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagsResponse) ProtoMessage() {}

func (x *TagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_article_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagsResponse.ProtoReflect.Descriptor instead.
func (*TagsResponse) Descriptor() ([]byte, []int) {
	return file_proto_article_proto_rawDescGZIP(), []int{1}
}

func (x *TagsResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type TopTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	N             int32                  `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopTagsRequest) Reset() {
	*x = TopTagsRequest{}
	mi := &file_proto_article_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopTagsRequest) ProtoMessage() {}

func (x *TopTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_article_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopTagsRequest.ProtoReflect.Descriptor instead.
func (*TopTagsRequest) Descriptor() ([]byte, []int) {
	return file_proto_article_proto_rawDescGZIP(), []int{2}
}

func (x *TopTagsRequest) GetN() int32 {
	if x != nil {
		return x.N
	}
	return 0
}

var File_proto_article_proto protoreflect.FileDescriptor

const file_proto_article_proto_rawDesc = "" +
	"\n" +
	"\x13proto/article.proto\x12\aarticle\"3\n" +
	"\aArticle\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04body\"\"\n" +
	"\fTagsResponse\x12\x12\n" +
	"\x04tags\x18\x01 \x03(\tR\x04tags\"\x1e\n" +
	"\x0eTopTagsRequest\x12\f\n" +
	"\x01n\x18\x01 \x01(\x05R\x01n2\xc7\x01\n" +
	"\x0eArticleService\x126\n" +
	"\vExtractTags\x12\x10.article.Article\x1a\x15.article.TagsResponse\x12?\n" +
	"\x10BatchExtractTags\x12\x10.article.Article\x1a\x15.article.TagsResponse(\x010\x01\x12<\n" +
	"\n" +
	"GetTopTags\x12\x17.article.TopTagsRequest\x1a\x15.article.TagsResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_article_proto_rawDescOnce sync.Once
	file_proto_article_proto_rawDescData []byte
)

func file_proto_article_proto_rawDescGZIP() []byte {
	file_proto_article_proto_rawDescOnce.Do(func() {
		file_proto_article_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_article_proto_rawDesc), len(file_proto_article_proto_rawDesc)))
	})
	return file_proto_article_proto_rawDescData
}

var file_proto_article_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_article_proto_goTypes = []any{
	(*Article)(nil),        // 0: article.Article
	(*TagsResponse)(nil),   // 1: article.TagsResponse
	(*TopTagsRequest)(nil), // 2: article.TopTagsRequest
}
var file_proto_article_proto_depIdxs = []int32{
	0, // 0: article.ArticleService.ExtractTags:input_type -> article.Article
	0, // 1: article.ArticleService.BatchExtractTags:input_type -> article.Article
	2, // 2: article.ArticleService.GetTopTags:input_type -> article.TopTagsRequest
	1, // 3: article.ArticleService.ExtractTags:output_type -> article.TagsResponse
	1, // 4: article.ArticleService.BatchExtractTags:output_type -> article.TagsResponse
	1, // 5: article.ArticleService.GetTopTags:output_type -> article.TagsResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_article_proto_init() }
func file_proto_article_proto_init() {
	if File_proto_article_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_article_proto_rawDesc), len(file_proto_article_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_article_proto_goTypes,
		DependencyIndexes: file_proto_article_proto_depIdxs,
		MessageInfos:      file_proto_article_proto_msgTypes,
	}.Build()
	File_proto_article_proto = out.File
	file_proto_article_proto_goTypes = nil
	file_proto_article_proto_depIdxs = nil
}
